---
title: "Air Quality Maps - Ozone"
output: 
  html_document:
    css: "assets/caaqs-styles.css"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Allows Rmd file to be run interactively and knit 
# without having to change the relative file locations all the time
library("here") 

# Tidyverse
library("dplyr")
library("tidyr")
library("purrr")
library("stringr")

# Mapping
library("leaflet")
library("sf")
library("geojsonio")
library("htmltools") # For HTML() function

# Functions to create popups and center map
library("envreportutils")
library("rcaaqs")

# Get css
css_caaqs_copy(folder = here("./leaflet_map/"), overwrite = TRUE)

# Assign labels, colours, and cutoffs using rcaaqs ----------------------------
#
# - This is a big messy block of code, but means that the units and labels
#   are automatically gathered from rcaaqs via achivement_levels and management_levels.
#   This means that changes only need to be made in rcaaqs.
# - All formating, colours, and markers are specified here
# - Factor levels are determined here as well, so that custom orders don't need
#  to be specified directly in the legends

# Ambient labels
labels_ambient <- achievement_levels %>%
  filter(str_detect(parameter, "o3")) %>%
  add_row(labels = "Insufficient Data", units = c(unique(.$units_html))) %>%
  mutate(colour = case_when(labels == "Achieved" ~ "#72a4cd",
                            labels == "Not Achieved" ~ "#cd7277",
                            labels == "Insufficient Data" ~ "#dbdbdb"),
         labels_full = if_else(!is.na(val_labels_html), 
                               paste0(labels, " (", val_labels_html, ")"),
                               labels),
         # Format the labels - add space before units
         labels_full = str_replace_all(labels_full, "(\\d+)(\\&mu)", "\\1 \\2"),
         labels = factor(labels, levels = c("Not Achieved", 
                                            "Achieved", "Insufficient Data"))) %>%
  arrange(labels) %>%
  mutate(labels_full = factor(labels_full, levels = unique(labels_full))) %>%
  select(labels, colour, labels_full, units_html)
  
# Management labels
labels_mgmt <- management_levels %>%
  filter(str_detect(parameter, "o3")) %>%
  mutate(colour = case_when(str_detect(labels, "Keeping") ~ "#ffffff",
                            str_detect(labels, "Deterioration") ~ "#bdbdbd",
                            str_detect(labels, "Exceedance") ~ "#737373",
                            str_detect(labels, "Achieving") ~ "#000000"),
         labels = val_labels_html,
         # Format the labels - add space before units, remove duplicate units
         labels = factor(labels, levels = labels),
         labels_full = labels,
         labels_full = str_replace_all(labels_full, "(\\d+)(\\&)", "\\1 \\2"),
         labels_full = str_remove(labels_full, units_html)) %>%
  arrange(labels) %>%
  select(labels, colour, labels_full, units_html) %>%
  mutate(icons = c("assets/marker_white.svg", "assets/marker_lightgrey.svg", 
                   "assets/marker_grey.svg", "assets/marker_black.svg"))

# Load and prep data ------------------------------------

## Stations - Get CAAQs and popups ---------------------------------------
stations <- read_sf(here("out/ozone_caaqs.geojson")) %>%
  # Count total stations, then omit those with insufficient data
  add_count(airzone) %>%
  filter(!is.na(metric_value_ambient)) %>%
  
  # Get management levels
  mutate(caaqs_mgmt = map2_chr(metric_value_ambient, metric,
                                 ~ as.character(rcaaqs:::cut_management(.x, .y,"breaks_h")))) %>%
  left_join(labels_mgmt, by = c("caaqs_mgmt" = "labels")) %>%
  rename(caaqs_legend = labels_full) %>%
  
  # Create popups
  mutate(p_az = airzone,
         p_station = site,
         p_station_id = site) %>%
  mutate(popup = popup_caaqs(
    ., type = "station", 
    units = units_html,
    metric_name = "Ozone Metric",
    standard_name = "Ozone Air Quality Standard"))

## Count stations
stns_n <- stations %>%
  st_set_geometry(NULL) %>%
  select(airzone, n) %>%
  distinct()

## Airzones - Get CAAQs and popups -----------------------------------
az <- st_read(here("./out/ozone_airzone.geojson")) %>%
  # Clarify names and add data
  rename(rep_station_id = rep_stn_id_ambient, n_years = n_years_ambient) %>%
  mutate(caaqs_ambient = replace_na(caaqs_ambient, "Insufficient Data")) %>%
  left_join(stns_n, by = "airzone") %>%
  
  # Get CAAQS labels
  left_join(labels_ambient, by = c("caaqs_ambient" = "labels")) %>%
  mutate(metric_value_ambient = as.numeric(metric_value_ambient)) %>%
  rename(caaqs_legend = labels_full) %>%
  
  # Create Airzone tooltips
  mutate(n = replace_na(n, 0),
         tooltip = map2(airzone, n, 
                        ~HTML(paste0(.x, "<br>", .y, 
                                     " Monitoring Station", 
                                     if_else(.y == 1, "", "s"))))) %>%
  # Create Airzone Popups
  mutate(p_az = airzone,
         p_station = rep_station_id,
         p_station_id = rep_station_id) %>%
  mutate(popup = popup_caaqs(
    ., type = "region", 
    units = units_html,
    metric_name = "Ozone Metric",
    standard_name = "Ozone Air Quality Standard"), 
    # Where insufficient data, keep the tool tip but omit the popup
    popup = if_else(caaqs_ambient == "Insufficient Data", 
                    list(NA_character_), popup))



# Formatting ----------------------

# Create palettes

pal_az <- labels_ambient %>%
  colorFactor(palette = .$colour, levels = .$labels_full)

# Create icons
icon_size <- 30
markers <- icons( # file locations have to be relative (can't use here())
  iconUrl = stations$icons,
  iconWidth = icon_size, iconHeight = icon_size,
  iconAnchorX = icon_size/2, iconAnchorY = icon_size,
  shadowUrl = "assets/marker_shadow.svg",
  shadowWidth = icon_size * 0.75, shadowHeight = icon_size * 0.75,
  shadowAnchorX = 1, shadowAnchorY = icon_size * 0.75)

# Popup Options
ppo <- popupOptions(autoPanPaddingTopLeft = c(10, 10),
                    autoPanPaddingBottomRight = c(10, 400),
                    closeOnEscapeKey = TRUE, 
                    keepInView = TRUE)
```


```{r, warning=FALSE}
leaflet(width = "900px", height = "700px", options = leafletOptions(minZoom = 5)) %>% 
  addProviderTiles(providers$CartoDB) %>%
  add_bc_home_button() %>%
  # Re-centre map on popup close
  set_bc_view_on_close() %>%
  
  # Add Airzone polygons
  addPolygons(data = az, 
              color = "white", weight = 2, opacity = 1, fillOpacity = 0.7,
              fillColor = ~pal_az(caaqs_legend),
              label = ~tooltip, 
              popup = ~popup,
              popupOptions = ppo) %>%
  
  # Add station markers
  addMarkers(data = stations,
             icon = markers, label = ~site, 
             popup = ~popup,
             # Stick to marker, not mouse
             labelOptions = labelOptions(sticky = FALSE, 
                                         offset = c(0, -icon_size/2))) %>%
  
  # Legend for polygons
  addLegend("bottomright",
            data = az,
            colors = labels_ambient$colour, 
            labels = labels_ambient$labels_full,
            opacity = 1, 
            title = htmltools::HTML("<h3>Air Zones</h3><h4>Ozone Air Quality Standard</h4>")) %>%
  
   # Custom legends for markers
  addLegend("bottomleft",
            colors = rev(labels_mgmt$colour),
            className = "info legend solid",
            labels = rev(labels_mgmt$labels_full),
            opacity = 1,
            title = htmltools::HTML("<h3>Ozone Monitoring Stations</h3><h4>Ozone Metric</h4>"))

```